name : データ転送実行
on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    if: startsWith(github.head_ref, 'transfer/')
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    env:
      AWS_ACCESS_KEY : ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9.11'
      - run: pip install poetry==1.2.0b1
      - run: poetry install --without dev
      - run: poetry run python main.py